spring:
  application:
    name: ms-order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${REALM_URL}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/order}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8082
  shutdown: graceful

orders:
  catalog-service-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders

  publish-order-events-job-cron: "*/5 * * * * *"
  new-orders-job-cron: "*/10 * * * * *"

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

swagger:
  api-gateway-url: http://localhost:8989/orders

OAUTH2_SERVER_URL: http://localhost:9191
REALM_URL: ${OAUTH2_SERVER_URL}/realms/bookstore
