version: '3.8'

services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog_db_container
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    volumes:
      - catalog_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  catalog_data: